### ISSUE TITLE
Error: Unable to resolve action `GeekyEggo/delete-artifact@2`, unable to find version `2`

### ISSUE THREAD

**Issue by jlarmstrongiv** [GeekyEggo/delete-artifact#11]
Example:
```yml
      - uses: geekyeggo/delete-artifact@2
        with:
          name: "**"
```
