### ISSUE TITLE
Not all artifacts matching the glob are deleted

### ISSUE THREAD

**Issue by joernott** [GeekyEggo/delete-artifact#22]
**Context:**
I am currently reworking a workflow to use with the v4 versions of upload/download-artifact and was relying heavily on adding content to artifacts before. So I settled for creating lots of unique little artifacts and combining them for the user at the very end of my workflow, where I use those tiny bits to generate a couple of reports. I use download-artifact to download all artifacts matching the pattern "testplan-*", then I generate some reports from all the snippets and combine everything into an artifact "testplan". Afterwards, I want to delete everything matching "testplan-*" to clean up.

**Problem:**
Some but not all artifacts matching the pattern are deleted. Example:
```
Run actions/download-artifact@v4
  with:
    pattern: testplan-*
    merge-multiple: true
```
downloads 32 artifacts, matching the various matrix runs. The subsequent
```
Run geekyeggo/delete-artifact@v4
  with:
    name: testplan-*
    useGlob: true
    failOnError: false
```
then deletes 18 of them, leaving the rest to dry. Do you have any idea, why this is happening?
