### ISSUE TITLE
Artifacts are deleted from produced at run time but not from Github API

### ISSUE THREAD

**Issue by ferasallaou** [GeekyEggo/delete-artifact#6]
Hey There,

I'm facing a weird issue while using the action
```
      - name: Delete Build artifacts
        if: "!!steps.release.outputs.version"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            webhooks
            graphql
```
So in my CI.yml file I've this code snippet, which seems to work cause when I check the Artifacts section inside my Github Action, I don't see those artifacts. However, If I make a call to `/repos/{owner}/{repo}/actions/artifacts` I can still them listed there.
is there anything we could do about that? or is it how Github Actions Artifacts works?
